version: "{build}"
clone_depth: 1
clone_folder: c:\gopath\src\github.com\rhysd\dotfiles-command
environment:
    GOPATH: c:\gopath
install:
    - echo %PATH%
    - echo %GOPATH%
    - go version
    - go env
    - go get -v -t -d ./...
build: off
test_script:
    - go test -v ./dotfiles-command/
deploy: off
